// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetUser.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Public {
  /// <summary>
  ///定义的服务
  /// </summary>
  public static partial class GetUserList
  {
    static readonly string __ServiceName = "Public.GetUserList";

    static readonly grpc::Marshaller<global::Public.pharm> __Marshaller_pharm = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Public.pharm.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Public.Userlist> __Marshaller_Userlist = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Public.Userlist.Parser.ParseFrom);

    static readonly grpc::Method<global::Public.pharm, global::Public.Userlist> __Method_GetList = new grpc::Method<global::Public.pharm, global::Public.Userlist>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetList",
        __Marshaller_pharm,
        __Marshaller_Userlist);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Public.GetUserReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GetUserList</summary>
    public abstract partial class GetUserListBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Public.Userlist> GetList(global::Public.pharm request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GetUserList</summary>
    public partial class GetUserListClient : grpc::ClientBase<GetUserListClient>
    {
      /// <summary>Creates a new client for GetUserList</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GetUserListClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GetUserList that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GetUserListClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GetUserListClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GetUserListClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Public.Userlist GetList(global::Public.pharm request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Public.Userlist GetList(global::Public.pharm request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetList, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Public.Userlist> GetListAsync(global::Public.pharm request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Public.Userlist> GetListAsync(global::Public.pharm request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetList, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GetUserListClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GetUserListClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GetUserListBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetList, serviceImpl.GetList).Build();
    }

  }
}
#endregion
